blog_app/urls.py
from django.urls import path
#importamos la vista
from .views import render_posts,post_detail

app_name='blog'

#cuando /posts/ es la ruta inicial
urlpatterns = [
    path('', render_posts,name='posts'),
    path('<int:post_id>',post_detail,name='post_detail'),
]

portfolio/urls.py
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings

from portfolio_app import views

urlpatterns = [
    path('admin/', views.administrator, name='administrator'),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('biography/', views.biography, name='biography'),
    path('blog/', include('blog_app.urls')),
    path('exhibition/', include('portfolio_app.urls')),
    path('administrator_login/', views.administrator_login, name='administrator_login'),
    path('administrator/', views.administrator, name='administrator'),
    path('administrator_detail/<int:exhibition_id>', views.administrator_detail, name='administrator_detail'),
    path('administrator_create/', views.create_exhibition, name='administrator_create'),

    path('administrator_update/<int:exhibition_id>/', views.update_exhibition, name='administrator_update'),
    path('administrator_delete/<int:exhibition_id>/', views.delete_exhibition, name='administrator_delete'),

]


handler404 = views.error_404
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_app/urls.py
from django.urls import path
#importamos la vista
from .views import exhibition_detail

app_name='exhibition'

#cuando /posts/ es la ruta inicial
urlpatterns = [
    path('<int:exhibition_id>',exhibition_detail,name='exhibition_detail'),
    
]

blog_app/models.py
from django.db import models
from django.db.models.fields import CharField, TextField, DateField
from django.db.models.fields.files import ImageField

import datetime

class Post(models.Model):
    title = CharField(max_length=100)
    description = TextField(max_length=10000, blank=True)
    image = ImageField(upload_to='blog_app/images')
    pdf_file = models.FileField(upload_to='blog_app/pdfs', null=True, blank=True)
    start_date = DateField(default=datetime.date.today, null=True, blank=True)
    end_date = DateField(default=datetime.date.today, null=True, blank=True)

portfolio_app/models.py
from django.db import models

class Exhibition(models.Model):
    title = models.CharField(max_length=100)
    ubication = models.CharField(null=True, max_length=150, blank=True)
    city = models.CharField(null=True, max_length=250, blank=True)
    date = models.DateField(null=True)
    description = models.TextField(max_length=10000)
    image = models.ImageField(upload_to='portfolio_app/images')
    video_url = models.URLField(blank=True, null=True)
    password = models.CharField(null=True, max_length=250, blank=True)
    hidden = models.BooleanField(default=False)

class Exhibition_View(models.Model):
    exhibition = models.ForeignKey(Exhibition, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(max_length=250, blank=True)
    image = models.ImageField(upload_to='portfolio_app/images')
    order = models.PositiveIntegerField(default=0, help_text='Order for display')

    class Meta:
        ordering = ['order']

class Biography(models.Model):
    title = models.CharField(max_length=100, default="Biography")


class Biography_Content(models.Model):
    biography = models.ForeignKey(Biography, on_delete=models.CASCADE)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    description = models.TextField(max_length=10000)

    class Meta:
        ordering = ['start_date']

portfolio_app/forms.py
from django import forms
from .models import Exhibition

class ExhibitionForm(forms.ModelForm):
    class Meta:
        model = Exhibition
        fields = '__all__'

blog_app/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.order_by('-start_date')
    return render(request, 'posts.html', {'posts': posts})


def post_detail(request,post_id):
    #Funcion de django para obtener un valor o retornar 404
    post=get_object_or_404(Post,pk=post_id)
    return render(request, 'post_detail.html',{'post':post})    

portfolio_app/views.py
from django.shortcuts import render,get_object_or_404
from .models import Exhibition,Biography_Content

def home(request):
    exhibitions = Exhibition.objects.filter(hidden=False).order_by('-date')
    context = {'exhibitions': exhibitions}
    return render(request, 'home.html', context)

def exhibition_detail(request,exhibition_id):
    exhibition = get_object_or_404(Exhibition, pk=exhibition_id)
    context = {'exhibition': exhibition}
    return render(request, 'exhibition_detail.html', context)    

def about(request):
    return render(request,'about.html')

def contact(request):
    return render(request,'contact.html')

def biography(request):
    biography_contents = Biography_Content.objects.all().order_by('biography__title')
    
    grouped_contents = {}
    
    for content in biography_contents:
        title = content.biography.title
        if title not in grouped_contents:
            grouped_contents[title] = {'title': title, 'contents': []}
        grouped_contents[title]['contents'].append(content)

    context = {'grouped_biography_contents': grouped_contents.values()}
    return render(request, 'biography.html', context)


def error_404(request, exception):
    return render(request, '404.html', {})

blog_app/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-rJSvKwONyyTi4gZGp0O7rckG9g4pgZ1f4r7Yfl" crossorigin="anonymous">

<div class="container text-center">
	  <header class="navbar-exhibition" style="z-index: 1;">

    <div class="navbar-exhibition">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <ul class="navbar-nav">
            
            <li class="nav-item">
              <a
                class="nav-link active navbar-item"
                aria-current="page"
                href="#Description"
                >Text</a
              >
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </header>
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <p class="description-post-tag" style="padding-top: 20px !important;">
                <strong>{{post.title}}</strong>
                {% if post.start_date %}
                    {{post.start_date|date:'Y'}}
                {% endif %}
                {% if post.end_date %}
                    -{{post.end_date|date:'Y'}}
                {% endif %}
            </p>
            {% if post.pdf_file %}
            <div style="position: fixed; bottom: 20px; right: 20px; z-index: 999;">
                <a href="#" class="pdf-download" onclick="togglePDFViewer()"><span>Descargar</span><span>PDF</span></a>
            </div>
            
            <div id="pdf-viewer" style="display: none;">
                <iframe src="{{post.pdf_file.url}}" style="width: 100%; height: 80vh;" allowfullscreen></iframe>
            </div>
            {% endif %}
            <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}" style="max-height: 500px;">
            <div style="height: 20px;"></div>
            <p class="text-left">{{post.description}}</p>

        </div>
    </div>
</div>

<!-- Modal -->
{% if post.pdf_file %}
<div class="modal fade" id="pdfModal" tabindex="-1" role="dialog" aria-labelledby="pdfModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pdfModalLabel">{{post.title}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <iframe src="{{post.pdf_file.url}}" style="width: 100%; height: 70vh;" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>
{% endif %}

<script>
    function togglePDFViewer() {
        $('#pdfModal').modal('toggle');
    }
</script>

<style>


    .pdf-download {
		background: #ffffff;
		border: solid 1px #e6e6e6;
		border-radius: 2px;
		display: inline-block;
		height: 100px;
		line-height: 100px;
		margin: 5px;
		position: relative;
		text-align: center;
		vertical-align: middle;
		width: 100px;
}

.pdf-download span {
		background: #f2594b;
		border-radius: 4px;
		color: #ffffff;
		display: inline-block;
		font-size: 11px;
		font-weight: 700;
		line-height: normal;
		padding: 5px 10px;
		position: relative;
		text-transform: uppercase;
		z-index: 1;
}

.pdf-download span:last-child {
		margin-left: -20px;
}

.pdf-download:before,
.pdf-download:after {
		background: #ffffff;
		border: solid 3px #9fb4cc;
		border-radius: 4px;
		content: '';
		display: block;
		height: 35px;
		left: 50%;
		margin: -17px 0 0 -12px;
		position: absolute;
		top: 50%;
		/*transform:translate(-50%,-50%);*/
		
		width: 25px;
}

.pdf-download:hover:before,
.pdf-download:hover:after {
		background: #e2e8f0;
}


.pdf-download:before {
		margin: -23px 0 0 -5px;
}

.pdf-download:hover {
		background: #e2e8f0;
		border-color: #9fb4cc;
}

.pdf-download:active {
		background: #dae0e8;
		box-shadow: inset 0 2px 2px rgba(0, 0, 0, .25);
}

.pdf-download span:first-child {
		display: none;
}

.pdf-download:hover span:first-child {
		display: inline-block;
}

.pdf-download:hover span:last-child {
		display: none;
}

</style>

{% endblock %}

blog_app/templates/posts.html
{% extends 'layout.html' %}
{% block content %}
<div class="container text-center">
    <div class="row row-cols-2" id="post-container">
    {% for post in posts|slice:":9" %} {# Limita a cargar solo las primeras 9 imágenes #}
    <div data-aos="fade-down" data-aos-easing="linear" data-aos-duration="700" class="col">
        <a href="{% url 'blog:post_detail' post.id %}">
            <img data-src="{{ post.image.url }}" class="img-fluid lazy" alt="{{ post.title }}">
        </a>
        <p class="description-post-tag">{{ post.title }}.{{ post.description|striptags|truncatechars:10 }}</p>
        <p class="description-post-tag">
            {% if post.start_date %}
            <span id="start-date-{{ post.id }}">{{ post.start_date|date:'m.d.y' }}</span>
            <script>
                // Código JavaScript para actualizar la fecha en tiempo real
                setInterval(function() {
                    var startDateElement = document.getElementById('start-date-{{ post.id }}');
                    var startDate = new Date('{{ post.start_date }}');
                    startDateElement.innerText = startDate.toLocaleDateString();
                }, 1000);
            </script>
            {% endif %}
            {% if post.end_date %}
            -<span id="end-date-{{ post.id }}">{{ post.end_date|date:'m.d.y' }}</span>
            <script>
                // Código JavaScript para actualizar la fecha en tiempo real
                setInterval(function() {
                    var endDateElement = document.getElementById('end-date-{{ post.id }}');
                    var endDate = new Date('{{ post.end_date }}');
                    endDateElement.innerText = endDate.toLocaleDateString();
                }, 1000);
            </script>
            {% endif %}
        </p>
    </div>
    {% endfor %}
    </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    var lazyImages = document.querySelectorAll('.lazy');
    var options = {
        rootMargin: '0px',
        threshold: 0.1
    };
    var imageObserver = new IntersectionObserver(function(entries, observer) {
        entries.forEach(function(entry) {
            if (entry.isIntersecting) {
                var image = entry.target;
                image.src = image.dataset.src;
                image.classList.remove('lazy');
                imageObserver.unobserve(image);
            }
        });
    }, options);

    lazyImages.forEach(function(image) {
        imageObserver.observe(image);
    });
});
</script>

{% endblock %}

portfolio_app/templates/crud/administrator_detail.html
{% extends 'layout.html' %} {% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.14.0/Sortable.min.js"></script>

<div class="container">
  <h1>Detalles de la Exposición</h1>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>Título:</th>
        <td ondblclick="makeEditable(this)">{{ exhibition.title }}</td>
      </tr>
      <tr>
        <th>Ubicación:</th>
        <td ondblclick="makeEditable(this)">{{ exhibition.ubication }}</td>
      </tr>
      <tr>
        <th>Ubicación:</th>
        <td ondblclick="makeEditable(this)">{{ exhibition.ubication }}</td>
      </tr>
      <tr>
        <th>Ciudad:</th>
        <td ondblclick="makeEditable(this)">{{ exhibition.city }}</td>
      </tr>
      <tr>
        <th>Fecha:</th>
        <td ondblclick="makeEditable(this)">{{ exhibition.date }}</td>
      </tr>
      <tr>
        <th>Descripción:</th>
        <td ondblclick="makeEditable(this)">{{ exhibition.description }}</td>
      </tr>
      <!-- Puedes agregar más campos aquí -->
      <tr>
        <th>Imágenes:</th>
        <td>
          <ul id="sortable">
            {% for image in exhibition.exhibition_view_set.all %}
              <li data-order="{{ image.order }}">
                <div class="drag-handle">
                  <i class="fas fa-bars"></i> <!-- Icono de tres rayas para arrastrar -->
                </div>
                <img src="{{ image.image.url }}" alt="{{ image.title }}" width="150">
              </li>
            {% endfor %}
          </ul>
        </td>
      </tr>
      

      <tr>
        <th>URL de Video:</th>
        <td ondblclick="makeEditable(this)">{{ exhibition.video_url }}</td>
      </tr>
      <tr>
        <th>Contraseña:</th>
        <td ondblclick="makeEditable(this)">{{ exhibition.password }}</td>
      </tr>
      <tr>
        <th>Oculto:</th>
        <td>
          <select id="hiddenSelect">
            <option value="true" {% if exhibition.hidden %} selected {% endif %}>Oculto</option>
            <option value="false" {% if not exhibition.hidden %} selected {% endif %}>No oculto</option>
          </select>
        </td>
      </tr>
      
    </tbody>
  </table>

  <!-- Botón para editar -->
  <a
    href="{% url 'administrator_detail' exhibition.id %}"
    class="btn btn-primary"
    >Editar</a
  >

  <!-- Botón para eliminar (con modal de confirmación) -->
  <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
    Eliminar
  </button>

  <!-- Modal de confirmación para eliminar -->
  <div
    class="modal fade"
    id="deleteModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="deleteModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">
            Confirmar Eliminación
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ¿Estás seguro de que deseas eliminar esta exposición?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Cancelar
          </button>
          <a
            href="{% url 'administrator_delete' exhibition.id %}"
            class="btn btn-danger"
            >Eliminar</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  /* Estilo para los campos de entrada */
  textarea {
    width: 100%; /* El ancho del textarea será igual al de la celda */
    height: 100%; /* La altura del textarea será igual al de la celda */
    resize: none; /* Evita que el usuario pueda redimensionar el textarea */
  }
</style>

<script>
  function makeEditable(cell) {
    const oldValue = cell.textContent;
    const textarea = document.createElement("textarea");
    textarea.value = oldValue;

    // Añade el campo de entrada
    textarea.addEventListener("blur", () => {
      cell.textContent = textarea.value;
    });

    // Establece el ancho y la altura del textarea para que coincidan con la celda
    textarea.style.width = cell.clientWidth + "px";
    textarea.style.height = cell.clientHeight + "px";

    cell.textContent = "";
    cell.appendChild(textarea);

    textarea.focus();
  }
</script>
<script>
  function editHidden() {
    const hiddenCheckbox = document.getElementById("hiddenCheckbox");
    hiddenCheckbox.removeAttribute("disabled");
  }
</script>


{% endblock %}

portfolio_app/templates/exhibition_detail.html
{%extends 'layout.html'%} {% block content%}
<script src="/static/js/fancybox.js"></script>
<style>
  .carousel-control-prev-icon,
  .carousel-control-next-icon {
    color: black !important;
  }

  .overlay {
    position: absolute;
    top: 20%;
    left: 95%;
    transform: translate(-50%, -50%);
    z-index: 1;
  }

  .fancybox-skin {
    padding: 0px !important;
  }

  .fancyMedia:hover {
    background-color: #00adefff !important;
  }

  .fancyMedia:hover .iconFancy {
    color: #000;
  }

  .overlay a {
    color: white;
    text-decoration: none;
    padding: 15px;
    border-radius: 5px;
    background-color: rgb(0, 0, 0);
  }
  .navbar-exhibition {
    position: fixed;
    top: 100;
    width: 100%;
    background-color: #ffffff;
  }
  .image-container {
    position: relative;
  }

  .text-overlay {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    background: rgba(255, 255, 255, 0.7); /* Fondo semi-transparente blanco */
    color: rgb(0, 0, 0);
    padding: 10px;
    box-sizing: border-box;
    text-align: center;
  }
</style>

<div class="container">
  <header class="navbar-exhibition" style="z-index: 1;">
    <div class="container-fluid">
      <p class="description-post-tag">
        <strong>
          {{exhibition.title}}. {% if exhibition.ubication %}
          {{exhibition.ubication}}, {% endif %} {% if exhibition.city %}
          {{exhibition.city}} {% endif %}
        </strong>
        ({{exhibition.date|date:'Y'}})
      </p>
    </div>
    <div class="navbar-exhibition">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <ul class="navbar-nav">
            {% if exhibition.exhibition_view_set.all %}
            <li class="nav-item">
              <a class="nav-link navbar-item" href="#Images">Works</a>
            </li>
            {% endif %} {% if exhibition.video_url %}
            <li class="nav-item">
              <a class="nav-link active navbar-item" href="#Video">Video</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a
                class="nav-link active navbar-item"
                aria-current="page"
                href="#Description"
                >Text</a
              >
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </header>

  <div class="container-fluid" style="padding-top: 75px">
    {% if exhibition.exhibition_view_set.all %}
    <section class="jumbotron text-center vh-100" id="Images">
      <div style="text-align: left">
        <p class="description-post-tag">
          <strong> Works </strong>
        </p>
        <div
          data-aos="fade-down"
          data-aos-easing="linear"
          data-aos-duration="700"
          id="carouselExampleIndicators"
          class="carousel slide"
        >
        <div class="lightbox" style="overflow-y: scroll; overflow-x: hidden; max-height: 860px; z-index: -1;">
          <div class="row">
              {% for exhibition_view in exhibition.exhibition_view_set.all %}
              <div class="col-lg-6">
                  <a class="gallery-image" rel="gallery" href="{{exhibition_view.image.url}}">
                    <img src="{{ exhibition_view.image.url }}" alt="Table Full of Spices" class="w-100 mb-2 mb-md-4 shadow-1-strong rounded" loading="lazy" />
                  </a>
      
                  <h5 style="font-size: 11px;"><strong>{{exhibition_view.title}}</strong></h5>
                  <p style="font-size: 11px;">{{exhibition_view.description}}</p>
              </div>
              {% endfor %}
          </div>
      </div>
      
        </div>
      </div>
    </section>
    <hr />
    {% endif %} {% if exhibition.video_url %}
    <section class="jumbotron text-center vh-100">
      <div style="text-align: left">
        <p class="description-post-tag">
          <strong> Video </strong>
        </p>

        {% if exhibition.password %}
        <p>Contraseña: {{exhibition.password}}</p>
        {% endif %}

        <div id="Video" style="padding: 75% 0 0 0; position: relative; z-index: -1;">
          <iframe
            src="{{exhibition.video_url}}"
            frameborder="0"
            allow="autoplay; fullscreen; picture-in-picture"
            allowfullscreen
            style="
              position: absolute;
              top: 0;
              left: 0;
              width: 100%;
              height: 100%;
            "
            title="{{exhibition.title}}"
          >
          </iframe>
          <div class="overlay">
            <a
              class="fancyMedia"
              data-fancybox-type="iframe"
              href="{{exhibition.video_url}}"
              ><i
                style="font-weight: bold"
                class="iconFancy bi bi-fullscreen"
              ></i
            ></a>
          </div>
        </div>
      </div>
    </section>
    <hr />
    {% endif %}
    <section class="jumbotron text-center vh-100">
      <div style="text-align: left; z-index: -1;">
        <p class="description-post-tag">
          <strong> Text </strong>
        </p>
      </div>
      <div
        data-aos="fade-down"
        data-aos-easing="linear"
        data-aos-duration="700"
        id="Description"
        style="padding: 14px; background-color: white"
      >
        <textarea
          style="
            height: 300px;
            width: 600px;
            background-color: white;
            resize: none;
            border: none;
            z-index: -1 !important;
          "
          disabled
        >
              {{exhibition.description}}
          </textarea
        >
      </div>
    </section>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/lozad@1.14.0/dist/lozad.min.js"></script>

<script>
  const exhibitionContainer = document.getElementById('carouselExampleIndicators');
  const observer = lozad('.lozad', {
    loaded: function (el) {
      el.classList.remove('lozad');
    }
  });

  // Observar las imágenes cuando se hace scroll
  window.addEventListener('scroll', function () {
    observer.observe();
  });
</script>

{% endblock %}

portfolio_app/templates/home.html
{% extends 'layout.html' %}
{% block content %}
<div class="container text-center">
  <div class="row row-cols-3" id="exhibition-container">
    {% for exhibition in exhibitions %}
    <div data-aos="fade-down" data-aos-easing="linear" data-aos-duration="700" class="col lozad">
      <picture>
        <a class="card-link" href="{% url 'exhibition:exhibition_detail' exhibition.id %}">
          <source data-srcset="{{ exhibition.image.url }}" type="image/svg+xml">
          <img data-src="{{ exhibition.image.url }}" class="img-fluid lozad" alt="Avatar">
        </a>
      </picture>
      <div class="exhibition-detail">
        <p class="card-title description-exhibition-tag"><i>{{ exhibition.title }}</i></p>
      </div>
      <div style="height: 20px;"></div>
    </div>
    {% endfor %}
  </div>
</div>

<script src="path/to/lozad.min.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const exhibitionContainer = document.getElementById('exhibition-container');
    const observer = lozad('.lozad', {
      loaded: function(el) {
        el.classList.remove('lozad');
      }
    });
    observer.observe();
  });
</script>

{% endblock %}

portfolio_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio - Marco Pando</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>   
    <link rel="stylesheet" type="text/css" href="/static/css/styleLayout.css">
    <link rel="stylesheet" type="text/css" href="/static/css/styleProject.css">

    <script src="https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js"></script>

    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script type="text/javascript" src="/static/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
    <link rel="stylesheet" href="/static/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
    <script type="text/javascript" src="/static/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
    
</head>
<body>
    <script>
        AOS.init();
      </script>

    <div class="container ">
      <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-propio">
          <div class="container-fluid">
            <a class="nav-link navbar-header" href="{% url 'home' %}">Marco Pando</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link navbar-item" href="{% url 'blog:posts' %}">News & Events</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link navbar-item" href="{% url 'biography' %}">Biography</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link navbar-item" href="{% url 'about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link navbar-item" href="{% url 'contact' %}">Contact</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
          <div class="row body-propio">

            <div class="col">
                {% block content%}

      
                {% endblock %}
            </div>
          </div>
      </div>
</body>
</html>